### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by chimilk** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#110] opened 2021-04-09 18:15 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#6

**In which task and step of the codelab can this issue be found?**
In task 4 (calculate the tip), and under "get the cost of service" step 1.
![step1](https://user-images.githubusercontent.com/82234038/114222653-d674d300-993c-11eb-8e51-776fb580563c.PNG)

**Describe the problem**

In the part where there is a ".text" added after the costOfService, once you complete the code in Android studio, it turns red and says that the .text is "unresolved reference: text". 
![Screenshot (60)](https://user-images.githubusercontent.com/82234038/114222870-1b990500-993d-11eb-993b-46fc9bff9900.png)
Even when I copy and paste the solution code that is found on the code lab, it still turns red. I have also made sure that the strings.xml, activity_main.xml, and build.gradle have been changed too, but it is still red. Could you explain how to get rid of the "unresolved reference: text"? Is there something that needs to be imported?

**Steps to reproduce?**
copy and paste all of the solution code into android studio
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 30

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-05-13 18:14
@chimilk 
Thank you for reaching out to us.

This issue is similar to https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution/issues/111
The binding variable should be: costOfServiceEditText

Please refer to the solution in #111 to see if that solves your issue.

**Comment by osuleymanova** [comment] 2021-11-23 01:19
The issue is closed as there was no further question or discussion.

**Closed by osuleymanova** 2021-11-23 01:19 UTC
Labels: question
