### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by zjensen1022** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#382] opened 2022-09-09 20:10 UTC
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?co

**In which task and step of the codelab can this issue be found?**
In "Writing your First Instrumentation Test" in step 2 of "Implement the test function"

**Describe the problem**
Simple typo, says "The UI component is different, and so the id name that is passed to the _withText()_ function is different"
but should say     "The UI component is different, and so the id name that is passed to the _withId()_ function is different"

**Steps to reproduce?**
Just a typo on the page.

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-09-14 17:22
Duplicate of #352 , #304

**Comment by osuleymanova** [comment] 2023-03-31 23:27
Hello @zjensen1022,

Thank you for reaching out to us and reporting this typo. It is fixed:

![Screenshot 2023-03-31 at 3 31 44 PM](https://user-images.githubusercontent.com/86437155/229249621-342665c1-0c4a-48da-8163-b08238e2a6b5.png)

**Closed as completed by osuleymanova** 2023-03-31 23:27 UTC
