### ISSUE TITLE
Could not view properly from app

### ISSUE THREAD

**Issue by Muhammad-Sharif-Ullah** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#315] opened 2022-03-07 18:35 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**

**Describe the problem**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-06-27 23:17
@Muhammad-Sharif-Ullah 
Thank you for reaching out to us. We appreciate if you could provide more details about the issue you faced.

**Comment by osuleymanova** [comment] 2022-09-14 21:53
@Muhammad-Sharif-Ullah 
 Unfortunately the issue is closed as there is no further update provided.

**Closed by osuleymanova** 2022-09-14 21:53 UTC
