### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by rahmadanu** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#278] opened 2022-01-09 17:03 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#8

**In which task and step of the codelab can this issue be found?**
Step 9. Challenge task

**Describe the problem**
It says we have to adjust the theme attributes based on the https://github.com/material-components/material-components-android-examples project. And then it provides the link https://github.com/material-components/material-components-android-examples/blob/develop/MaterialThemeBuilder/README.md for the adjustments. The problem is that the link is not found and I don't have the guide for this challenge. Please make it more clear so that we can practice on this fun challenge :). Well pardon me I just checked that it appeared only if the language page is changed to my native language "Indonesian", when I changed to English there is no challenge provided but learn more instead. So I hope it helps you to make the translation feature even better.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-29 00:29
Duplicate of #241 , #222 , #219

**Closed by osuleymanova** 2022-03-29 00:29 UTC

**Comment by osuleymanova** [comment] 2022-03-29 00:31
@rahmadanu 
Thank you for reaching out to us and reporting this localization issue. The actions for fixing it will be taken soon.
