### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by kresohr** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#164] opened 2021-06-22 07:02 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
3. View Binding - Bottom of the page

**Describe the problem**
I believe there is a typo in the explanation of how the name of the binding class is generated. It says that the name of the XML file is converted to camel case, however, the name is actually converted to pascal case as the view-binding documentation will confirm: https://developer.android.com/topic/libraries/view-binding

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2
2. Click on... X (Scroll to the bottom)
![Untitled](https://user-images.githubusercontent.com/48351282/122878939-9bc5e880-d338-11eb-8af6-e2e0dfc49b2e.png)

3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-08-23 22:39
Duplicate of #126, #102

**Comment by osuleymanova** [comment] 2021-08-30 22:08
@kresohr 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**Closed by osuleymanova** 2021-08-30 22:08 UTC
