### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by obiscolly50** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#166] opened 2021-06-28 04:26 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Step 6

**Describe the problem**
Incorrectly states that the foreground has a gradient which is why it is included in drawable-v24. The background has gradient and not the foreground

**Steps to reproduce?**
1. Go to...Section titled **Move vector drawable files into -v26 directory**
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-28 20:16
Duplicate of #161, #165

**Closed by osuleymanova** 2022-03-28 20:16 UTC
