### ISSUE TITLE
Android Basics: Done/Next button misssing - classes-and-inheritance

### ISSUE THREAD

**Issue by licofiS** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#52] opened 2020-12-16 21:16 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance#7

**In which task and step of the codelab can this issue be found?**
In learn more section there is no done button at the bottom

**Describe the problem**
After every section at the end of that layout and learn more section there is done option but there it is not present in that page

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-25 22:50
@
The issue is closed as outdated.

**Closed by osuleymanova** 2022-03-25 22:50 UTC
Labels: In Progress
