### ISSUE TITLE
Android Basics: change-app-theme / tip-calculator: wrong color resource

### ISSUE THREAD

**Issue by croworc** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#66] opened 2021-01-20 09:31 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#4

**Associated project repo**
https://github.com/google-developer-training/android-basics-kotlin-tip-calculator-app-solution

**In which task and step of the codelab can this issue be found?**
Task: `(5) Dark theme`
Step: `Update the dark version of your theme`
&nbsp;&nbsp; Item               #`5 Change colorSecondaryVariant to @color/blue_light.` 
&nbsp;&nbsp; should instead be: #`5 Change colorSecondaryVariant to @color/blue_dark.`

Also update accordingly:
Task: `(6) Solution code`
Step: `values-night/themes.xml (app > res > values > themes > themes.xml (night))`

**Describe the problem**
For `themes.xml (night)` the value for the attribute  `colorSecondaryVariant` should be `blue_dark` instead of `blue_light`.
Change in repository from:
    ` <item name="colorSecondaryVariant">@color/blue_light</item>`
to:
    ` <item name="colorSecondaryVariant">@color/blue_dark</item>`

Also, the codelab text should be updated accordingly, as shown above.

**Steps to reproduce?**
1. Go to... N/A
2. Click on... N/A
3. See error... N/A

**Versions**
_Android Studio version:_  N/A
_API version of the emulator:_  N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._  N/A

**Comment by jtavva** [comment] 2021-03-01 22:20
@croworc 
Thank you for reaching out to us.
`color/blue_light` and `color/blue_dark` are just the names of the colors.  For night theme it is recommended to use light colors so that they are visible. 
The current code snippet in the codelab is correct and no changes are needed.

**Comment by croworc** [comment] 2021-03-02 09:36
@jtavva 
Thanks for replying!
The point that I've been trying to make is that supposedly

&nbsp;&nbsp;&nbsp;&nbsp;  `colorSecondary` &nbsp;&nbsp;&nbsp;&nbsp; and
&nbsp;&nbsp;&nbsp;&nbsp;  `colorSecondaryVariant`

should be ***different*** colors.
In the code / codelab however, these are the same color:
&nbsp;&nbsp;&nbsp;&nbsp; @color/blue_light

I assume, technically that doesn't really matter for the night theme, as the secondary color variant wouldn't show up anywhere in this simple UI. Just wanted to point to the general (albeit minor) issue. Or am I missing something?
Or maybe I'm just overly picky here. :smile:

Cheers!

**Comment by osuleymanova** [comment] 2022-03-30 23:27
The issue is closed as resolved and outdated.

**Closed by osuleymanova** 2022-03-30 23:27 UTC
