### ISSUE TITLE
Android Basics issue: Incorrect instruction and function name

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#327] opened 2022-03-23 14:19 UTC
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Write Instrumentation Tests - [4. Writing Your First Instrumentation Test](https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3) - Step 4 of first section

**Describe the problem**
The testing function is initially called 'calculate_20_percent_tip()' but is later referred to and given in code as 'calculate_default_tip()

**Steps to reproduce?**
1. Go to... https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3
2. Scroll to... step 4
3. See error... Crossreferencing with later instructions in code in subsection "Implement the Test function"

**Versions**
_Android Studio version:_ Android Studio Bumblebee | 2021.1.1 Patch 2
_API version of the emulator:_ 

**Additional information**
Initial instruction:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2918781/159721089-9f8fbdd6-bd13-4178-adb6-b58cc237ba80.png">
Later code:
<img width="714" alt="image" src="https://user-images.githubusercontent.com/2918781/159721290-06c3b558-b246-4314-80a0-c7a76a252b63.png">
<img width="576" alt="image" src="https://user-images.githubusercontent.com/2918781/159721413-f847a960-4115-44c5-a905-5214c293fd97.png">

**Comment by osuleymanova** [comment] 2022-03-30 22:47
Duplicate of #306, #286, #280, #277, #269, #251, #250, #249
@profess 
Thank you for reaching out to us. The typo is fixed and will be published soon.
![Screen Shot 2022-03-30 at 3 42 10 PM](https://user-images.githubusercontent.com/86437155/160943437-48d6f21e-0437-431a-a9b0-a8080af3f8da.png)
![Screen Shot 2022-03-30 at 3 41 41 PM](https://user-images.githubusercontent.com/86437155/160943442-b102fc78-f077-44ce-beb1-535fdbfad857.png)

**Closed as completed by osuleymanova** 2022-03-30 22:47 UTC
