### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by samerghabra** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#114] opened 2021-04-12 15:11 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2

**In which task and step of the codelab can this issue be found?**

https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#2
**Describe the problem**
error when i add this line of code 
![Capture](https://user-images.githubusercontent.com/5702929/114417665-74290600-9bba-11eb-9a75-e5908ef46efc.PNG)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-05-13 18:09
@samerghabra 
For further assistance, can you please copy paste the error you are seeing?
Thank you

**Comment by osuleymanova** [comment] 2021-11-24 20:26
The issue is closed as within 6 months the user didn't reply.

**Closed by osuleymanova** 2021-11-24 20:26 UTC
Labels: question
