### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by DutchSammmie** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#6] opened 2020-09-28 17:26 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
step 5

**Describe the problem**
typo: "The floor area of a circular dwelling is 2 * PI * radius." should be "PI * radius * radius" or "PI * radius2" (square)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by GeneAndGoogle** [comment] 2020-09-28 20:05
Duplicate of #3

**Closed by GeneAndGoogle** 2020-09-28 20:05 UTC
