### ISSUE TITLE
Android Basics issue: function names are wrong

### ISSUE THREAD

**Issue by RedStoner** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#308] opened 2022-02-22 02:36 UTC
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
Write instrumentation Tests step 4

**Describe the problem**
function created here is different and confused me alot. You first tell me to create a function like so - 
"Next, you need to write the test logic itself. Create a function and call it calculate_20_percent_tip() and annotate it with the @Test annotation."
then just a bit down, you state - 
"Now, in the calculate_default_tip() function in your test class, you can write the test logic."
This calculate_default_tip() function does not exist at this point. 

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-30 23:18
Duplicate of #306, #286, #280, #277, #269, #251, #250, #249
@RedStoner 
Thank you for reaching out to us. Already handled.

**Closed by osuleymanova** 2022-03-30 23:18 UTC
