### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by aatirmizi** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#149] opened 2021-05-16 04:37 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
3. view binding last para

**Describe the problem**
in the para
"Note: The name of the binding class is generated by converting the name of the XML file to **_camel case_** and adding the word "Binding" to the end. Similarly, the reference for each view is generated by removing underscores and converting the view name to camel case. For example, activity_main.xml becomes ActivityMainBinding, and you can access @id/text_view as binding.textView." 

it should be PacalCase instead of camel Case

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-08-23 23:02
Duplicate of #102, #126, #164

**Comment by osuleymanova** [comment] 2021-08-30 22:09
@aatirmizi 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**Closed by osuleymanova** 2021-08-30 22:09 UTC
