### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by noblecoder11** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#219] opened 2021-10-23 05:04 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#8

**In which task and step of the codelab can this issue be found?**
Challenge Task

**Describe the problem**
Last link in the challenge section named 'MaterialThemeBuilder/README.md' is not working.
This is the link: https://github.com/material-components/material-components-android-examples/blob/develop/MaterialThemeBuilder/README.md

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-28 18:54
Duplicate of #222, #241

**Closed by osuleymanova** 2022-03-28 18:54 UTC
