### ISSUE TITLE
Kotlin Playground Empty & not editable

### ISSUE THREAD

**Issue by ralph-embalsado** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#121] opened 2021-04-18 14:10 UTC
**URL of codelab**

https://developer.android.com/training/kotlinplayground

**In which task and step of the codelab can this issue be found?**

3. Create a base class, item1

**Describe the problem**

The Kotlin playground can't be edited. No codes are available on the link.

**Steps to reproduce?**
1. Go to Kotlin Basic
2. Click on Module 2
3. Click on Create a Base class
4. See item 1
5. Click the link directing to Kotlin playground
3. See error

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-04-20 18:25
@ralph-embalsado 
Thank you for reaching out to us.
The link given in the codelab is correct: https://developer.android.com/training/kotlinplayground
Try changing the code inside the code block.

![image](https://user-images.githubusercontent.com/24260141/115443515-3898c800-a1c8-11eb-9ecc-4aaa156a3ca4.png)




**There won't be any code in the playground, you need to copy-paste from the codelab.**

Alternatively you can use the following Kotlin playground:
https://play.kotlinlang.org/

If you still face issues please send in the screenshots.

**Comment by osuleymanova** [comment] 2021-11-24 20:20
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2021-11-24 20:20 UTC
Labels: question
