### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by aljohnston112** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#86] opened 2021-03-14 21:32 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Fit a carpet into a round dwelling
Steps 2 and 3

**Describe the problem**
calculateMaxCarpetSize() does not take the number of floors in the RoundTower into account.

**Steps to reproduce?**
N/A

**Versions**
N/A

**Additional information**
N/A

**Comment by jtavva** [comment] 2021-03-16 19:33
@aljohnston112 
Thank you for pointing this.
To keep things simple, we are calculating carpet size for a single floor.

**Comment by osuleymanova** [comment] 2021-11-24 01:44
The issue is closed as no further comments followed.

**Closed by osuleymanova** 2021-11-24 01:44 UTC
