### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by DTselikis** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#222] opened 2021-10-25 12:03 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#8

**In which task and step of the codelab can this issue be found?**
9 Challenge Task

**Describe the problem**
MaterialThemeBuilder is not in the given GitHub repo. Also the provided link for the MaterialThemeBuilder README.md leads
to a 404 GitHub page.

**Steps to reproduce?**
1. Go to "9 Challenge Task"
2. Click on "MaterialThemeBuilder/README.md"
3. See error...

**Comment by osuleymanova** [comment] 2022-03-28 18:53
Duplicate of #241

**Closed as completed by osuleymanova** 2022-03-28 18:53 UTC
