### ISSUE TITLE
tipResult unresolved reference

### ISSUE THREAD

**Issue by CaptainPol** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#83] opened 2021-03-04 08:45 UTC
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#5

I am writing the MainActiviity .kt file

I wrote the code exactly as in the tutorial.
 
The variable tipResult is marked as an error : unresolved reference

![Schermafbeelding 2021-03-04 084304](https://user-images.githubusercontent.com/24776279/109936585-fbcf4b00-7cc5-11eb-8ca2-74ce80b05452.png)

**Comment by jtavva** [comment] 2021-03-16 20:06
@CaptainPol 

Thank you for reaching out to us.

Plese check your activity_main.xml layout file, you should have a text view named tip_result.
after adding the textview, please rebuild the project once again. 

    <TextView
        android:id="@+id/tip_result"
        style="@style/Widget.TipTime.TextView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="8dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintTop_toBottomOf="@id/calculate_button"
        tools:text="Tip Amount: $10"
        />

**Comment by osuleymanova** [comment] 2021-11-23 01:26
The issue is closed as resolved.

**Closed by osuleymanova** 2021-11-23 01:26 UTC
Labels: invalid
