### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by jh115424** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#283] opened 2022-01-14 23:51 UTC
**URL of codelab**
      [ https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?authuser=1&continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%3Fauthuser%3D1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3](url)

**In which task and step of the codelab can this issue be found?**
      in step 4 of calculate the tip

**Describe the problem**
      it says Formatting string 'tip_amount' is not a valid format string so it should not be passed to String.format.
   copy and paste of actual code YOU told me to put, and I can't finish the calculator because it will crash with this.

     val formattedTip = NumberFormat.getCurrencyInstance().format(tip)
        binding.tipResult.text = getString(R.string.tip_amount, formattedTip)
    }
}

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by moisedk** [comment] 2022-01-16 16:27
The issue is not in the kotlin code. The error message means that `tip_amount` (in the string resources) does not include a placeholder for `formatedTip`. Format it using the % sign, like this: 
`<string name="tip_amount">Tip Amount: %s</string>`.  
`getString(R.string.tip_amount, formattedTip)` will replace the the % sign with the second argument, `formatedTip`.

**Comment by jh115424** [comment] 2022-01-16 20:08
Yes, it worked!    Thanks so much for the fast reply too!

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by osuleymanova** [comment] 2022-03-31 00:07
The issue is closed as resolved.

**Closed by osuleymanova** 2022-03-31 00:07 UTC
