### ISSUE TITLE
Android Basics: change-app-theme (Broken URL)

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#217] opened 2021-10-15 23:39 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme

**In which task and step of the codelab can this issue be found?**
Step 9, the Challenge Task, at the very last section of the page (Customize the theme)

**Describe the problem**
The link to MaterialThemeBuilder/README.md does not work.

**Steps to reproduce?**
1. Go to [Step 9 of the codelab](https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme#8).
2. Scroll to the "Customize the theme" section. Click on MaterialThemeBuilder/README.md. (The sentence begins with "Follow the instructions in...")
3. See the 404 error.

**Versions**
_Android Studio version:_ N/A
_API version of the emulator:_ N/A

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
<img width="1211" alt="Screen Shot 2021-10-15 at 7 27 29 PM" src="https://user-images.githubusercontent.com/11078178/137564113-8513f45e-ced0-48a7-9d75-7995095acb09.png">

**Comment by osuleymanova** [comment] 2022-03-28 18:55
Duplicate of #241 , #222 , #219

**Closed as completed by osuleymanova** 2022-03-28 18:55 UTC
