### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by idoamir** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#79] opened 2021-02-27 15:23 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
Fit a carpet into a round dwelling

**Describe the problem**
The formula you cite for a rectangle inscribed in a circle, I believe is wrong, and should be (2r^2), to be translated into representation with Diameter as (D^2)/2 and *not* [sqrt(D^2)/2] .

See:  https://geometryhelp.net/square-inscribed-in-a-circle/

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by eitarox** [comment] 2021-03-13 13:56
I agree with it.
If you want to use a squrt method in the lesson, you could set another word, e.g., **carpetSideLength** instead of **carpetSize**

**Comment by idoamir** [comment] 2021-03-13 17:10
Thanks. My idea was to let you know there is a mistake, so you can fix it for everyone... :-)

**Comment by osuleymanova** [comment] 2021-11-24 01:55
Duplicate of #67

**Comment by osuleymanova** [comment] 2021-11-24 01:56
@idoamir 
Thank you for reaching out to us. The issue is fixed and will be published soon:
fun calculateMaxCarpetLength(): Double {
    return sqrt(2.0) * radius
}

**Closed by osuleymanova** 2021-11-24 01:56 UTC
