### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by kkregar** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#9] opened 2020-09-30 10:44 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
5. Modify classes in the hierarchy
Implement floorArea() for RoundHut

**Describe the problem**
"The floor area of a circular dwelling is 2 * PI * radius."
I think 2 * PI * radius is a circumference. The area is PI * radius * radius
Further in the code samples it is correct.

**Comment by GeneAndGoogle** [comment] 2020-09-30 17:37
Duplicate of #3

**Closed by GeneAndGoogle** 2020-09-30 17:37 UTC
