### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by aaoconno** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#215] opened 2021-09-25 12:05 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Step 3 View binding.

**Describe the problem**
while following code lab to enable viewBinding I get build warning, "Access to 'viewBinding' exceeds its access rights"
Example code is written in Kotlin when Groovy was expected.

**Steps to reproduce?**
Enable view binding
1. Open the app's build.gradle file ( Gradle Scripts > build.gradle (Module: Tip_Time.app) )
2. In the android section, add the following lines:

buildFeatures {
    viewBinding = true
}

3. See error... build warning, Access to 'viewBinding' exceeds its access rights.  Build.Gradle is expecting Groovy not Kotlin. 
4. Remove equal sign to 'viewBinding  true'. to clear the warning.

**Versions**
_Android Studio version:_ 2020.3.1 patch 2
_API version of the emulator:_ 31.0.0

**Additional information**
none

**Comment by osuleymanova** [comment] 2021-11-22 23:17
Duplicate of #216

**Comment by osuleymanova** [comment] 2021-11-22 23:19
@aaoconno 
Thank you for reaching out to us. This error message "Access to 'viewBinding' exceeds its access rights" could happen if you are using the Groovy for gradle scripts. In this case your suggested solution to remove the equal sign works well. For Kotlin gradle the code snippet provided in the codelab is correct. Hope this clarifies the situation.
Happy coding!

**Closed by osuleymanova** 2021-11-22 23:19 UTC
