### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by nicola-masarone** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#128] opened 2021-04-29 15:00 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Change the app icon

**Describe the problem**
![NewIssue-1](https://user-images.githubusercontent.com/50139878/116571895-c7fe5380-a90b-11eb-8c6f-16be150df9b2.png)

"you may notice that the **_foreground asset_** is located in the **_drawable-v24 folder_**, while the **_background asset_** is in the **_drawable folder_**. The reason is because the foreground asset contains a gradient, which was available starting in the Android 7.0 release (also known as API version 24, hence the -v24 resource qualifier). The background asset doesn't contain a gradient, so that can go in the base drawable folder."

That's not correct because the **_foreground asset_** is located in the **_drawable folder_** while the **_background asset_** is in the **_drawable-v24 folder_** as clearly explained in the following instructions.

![NewIssue-2](https://user-images.githubusercontent.com/50139878/116572085-f0864d80-a90b-11eb-9fe6-9489ca884a26.png)

**Steps to reproduce?**
1. Go to...documentation
2. See error... in the **_Move vector drawable files into -v26 directory_** section

**Versions**
_Android Studio version:_ n/a
_API version of the emulator:_ n/a 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-28 21:52
Duplicate of #161, #165, #166

**Closed by osuleymanova** 2022-03-28 21:52 UTC
