### ISSUE TITLE
Android Basics: DAC navigation -- change-app-theme

### ISSUE THREAD

**Issue by 0lmagalhaes0** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#77] opened 2021-02-22 10:44 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#8

**In which task and step of the codelab can this issue be found?**
End of every codelab in every pathway so far

**Describe the problem**
When I finish the codelabs and click next, I'm taken to the quiz section instead of the next codelab. So I have to manually return to the current pathway, open my last codelab, click "done" and then manually start the next codelab. I imagine the intention was for all this to happen in the "Next" button by the end of any codelab.

Also, since I'm here, the pathways are quite difficult to find in the developer platform. I guess I was lucky to find it in the first place, because every time I try to get there by "conventional navigation", I end up somewhere else. I could only continue the course because I saved the URL, otherwise it seems I navigate in circles between kotlin and android studio without ever finding these pathways that I'm in.

And kudos to you guys, the course is awesome!!! I feel like if this was more mainstreamed, everybody would be doing it. (Kinda glad it isn't, so the knowledge I'm acquiring has more value.) With this, who needs Coursera, EDX, Udacity, etc?!.. The learning process is so smooth, objective and effective it almost feels not like learning but like going thru a long and complete cheatsheet. My favorite learning tool ever!

**Steps to reproduce?**
1. Go to... any first codelab from any pathway
2. Click on... "next", when in the last step of the codelab
3. See error... quiz page, instead of 1) mark first codelab as "done" and 2) proceed to next codelab page

**Versions**
_Android Studio version:_ NA
_API version of the emulator:_ NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-11-24 23:46
@0lmagalhaes0 
Thank you for reaching out to us and sharing your feedback. We appreciate it. 
As for the wrong redirection of the button "Next" in the end of the codelab, could you please let us know in what OS and browser it happens?

**Comment by osuleymanova** [comment] 2022-03-25 22:51
@0lmagalhaes0 
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-03-25 22:51 UTC
