### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by chadbradley94** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#97] opened 2021-04-01 23:50 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#3 

**In which task and step of the codelab can this issue be found?**
the last step just before the task "Get the tip percentage"

**Describe the problem**
The text says:
"At this point, the calculateTip() method should like this:"

What I assume it should say:
"At this point, the calculateTip() method should _look_ like this:"

**Steps to reproduce?**
1. Go to...
![Screenshot 2021-04-01 175005](https://user-images.githubusercontent.com/81783318/113365193-b7f65280-9312-11eb-92d2-063bb7485d43.png)

2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-08-23 22:09
Duplicate of #69

**Comment by osuleymanova** [comment] 2021-11-23 01:24
@chadbradley94 
Thank you for reaching out to us. The issue is fixed and published.

**Closed by osuleymanova** 2021-11-23 01:24 UTC
