### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by KitStonierBDX** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#267] opened 2021-12-30 18:41 UTC
[**URL of codelab**](https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3)

Write instumentation step 3

no new line in code example 
``` @get:Ruleval activity = ActivityScenarioRule(MainActivity::class.java) ```

**Versions**
_Android Studio version:_ NA
_API version of the emulator:_ NA

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._
![image](https://user-images.githubusercontent.com/57118042/147779533-167fbd45-df6f-48d6-a804-c90d077c0741.png)

**Comment by osuleymanova** [comment] 2022-03-31 00:25
Duplicate of #271, #266, #265
@KitStonierBDX 
The typo is fixed. Thanks for reporting it.

**Closed by osuleymanova** 2022-03-31 00:25 UTC
