### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by adamsrosco** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#115] opened 2021-04-13 05:59 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
Task: 3, Step: Enable view bindings

**Describe the problem**
Syntax has changed. I get a build error when enabling buildfeatures, since discovered it was changed to viewBinding.

buildFeatures {
    viewBinding true
}

is replaced with: 

viewBinding {
    enabled true
}

**Steps to reproduce?**
1. Go to build.gradle file
2. add the buildFeature code snippet
3. See error: Could not find method buildFeatures() for arguments

**Versions**
Android Studio 4.1.3 

**Additional information**

**Comment by jtavva** [comment] 2021-04-20 20:28
@adamsrosco 
Thank you for reaching out to us.
The correct syntax to enable the viewbinding is as follows (as mentioned in the codelab):

```
buildFeatures {
        viewBinding = true
    }
```
Please use the above code and let us know if you are still facing issues.

**Comment by aicarambazigalo** [comment] 2021-08-29 20:13
> 
> 
> @adamsrosco
> Thank you for reaching out to us.
> The correct syntax to enable the viewbinding is as follows (as mentioned in the codelab):
> 
> ```
> buildFeatures {
>         viewBinding = true
>     }
> ```
> 
> Please use the above code and let us know if you are still facing issues.

while that works(and it is what the codelab currently suggests), it seems to be for the Kotlin version instead of Gradle version, or whatever, as per this answer https://stackoverflow.com/questions/68569379/access-to-viewbinding-exceeds-its-access-rights/68569684#68569684
which recommends removing the equal sign, otherwise (with the '=' sign) there's a hint/warning that says `Access to 'viewBinding' exceeds its access rights` in latest Android Studio Arctic Fox.

Without '=' sign, it's all fine for me, however it seems the OP suggests otherwise hmm.. odd

**Comment by aicarambazigalo** [comment] 2021-08-29 21:20
Ok, this is how you know if your `build.gradle` is Groovy (or is Kotlin), put these lines at its top:

```gradle
buildscript {
    //so this is Groovy not Kotlin:
    4.times { println "I'm Groovy"}
    repeat(4) { println("I'm Kotlin") } // Could not find method repeat() for arguments [4 ...
}
```
and after you Sync, if it fails with `Could not find method repeat() for arguments [4 ...` then it's NOT Kotlin, thus it's Groovy, and you can comment out that `repeat(4)` line and Sync again to see that it works for printing `I'm Groovy`.

Therefore now that you know it's Groovy, you know NOT to use the '=' syntax for enabling `viewBinding` mentioned under Kotlin in its doc here: https://developer.android.com/topic/libraries/view-binding#groovy

Yup, this was confusing for newbies like me.
Credit/Extra reading: https://docs.gradle.org/current/userguide/tutorial_using_tasks.html#sec:dynamic_tasks


Now if the codelab could be corrected that would be nice. And it would get rid of that `Access to 'viewBinding' exceeds its access rights` warning, and a bunch of github issues could be closed.

**Comment by adamsrosco** [comment] 2021-08-30 08:07
Awesome, Thank you very much.
[image: Rosco Adams]
<https://za.linkedin.com/in/adamsrosco?trk=profile-badge-cta>

**Comment by osuleymanova** [comment] 2021-11-23 01:15
The issue is closed as there was no further questions or discussion.

**Closed by osuleymanova** 2021-11-23 01:15 UTC
Labels: question
