### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by MedoRedo** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#220] opened 2021-10-23 09:16 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-icon?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-icon#5

**In which task and step of the codelab can this issue be found?**
Change the app icon

**Describe the problem**

It was written in the lab that:
"Depending on the min SDK of your app, you may notice that the foreground asset is located in the drawable-v24 folder, while the background asset is in the drawable folder. The reason is because the foreground asset contains a gradient, which was available starting in the Android 7.0 release (also known as API version 24, hence the -v24 resource qualifier). The background asset doesn't contain a gradient, so that can go in the base drawable folder."

I think it should be the background that contains a gradient not the foreground.

**Comment by osuleymanova** [comment] 2022-03-28 20:16
Duplicate of #161, #165, #166

**Comment by osuleymanova** [comment] 2022-03-28 20:17
@MedoRedo 
Thank you for reaching out to us. The content update will be published soon.

**Closed by osuleymanova** 2022-03-28 20:17 UTC
