### ISSUE TITLE
Android Basics issue: Confusing instructions in test practice codelab

### ISSUE THREAD

**Issue by jdelles** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#326] opened 2022-03-21 15:31 UTC
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3

**In which task and step of the codelab can this issue be found?**
4. Next, you need to write the test logic itself. Create a function and call it calculate_20_percent_tip()...

**Describe the problem**
The instructions state Create a function... caclculate_20_percent_tip() but later instructions refer to calculate_default_tip() and the solution code matches calculate default tip. This was confusing as a user, I felt like I had missed a step and reread the directions several times. 

**Steps to reproduce?**
N/A - instructions error

**Versions**
N/A - instructions error

**Additional information**
N/A - instructions error

**Comment by osuleymanova** [comment] 2022-03-31 00:34
Duplicate of #306, #286, #280, #277
@jdelles 
Thank you for reaching out to us. Our apologies for the typo and inconvenience caused. Now it is fixed and will be published soon.
![Screen Shot 2022-03-30 at 3 42 10 PM](https://user-images.githubusercontent.com/86437155/160952975-0f334174-fe0d-454e-858c-de9ca6e9b9d6.png)
![Screen Shot 2022-03-30 at 3 41 41 PM](https://user-images.githubusercontent.com/86437155/160952991-a34b8ed5-4871-4bcc-85ca-a44937351470.png)

**Closed as completed by osuleymanova** 2022-03-31 00:34 UTC
