### ISSUE TITLE
Android Basics issue:

### ISSUE THREAD

**Issue by rishisin999** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#271] opened 2022-01-02 04:27 UTC
**https://developer.android.com/codelabs/android-basics-kotlin-write-instrumentation-tests?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-write-instrumentation-tests#3**

**In which task and step of the codelab can this issue be found? 
  This issue can be found in the 4rth task(Writing your first instrumentation test) and at the 3rd step **

**@get:Ruleval activity = ActivityScenarioRule(MainActivity::class.java)
   this line of code is having an error in android studio and there should be a space after @get:Rule and before val 
   @get:Rule val activity = ActivityScenarioRule(MainActivity::class.java)**

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-29 15:58
Duplicate of #266 , #265 
@rishisin999 
Thank you for reaching out to us. The issue is fixed and published:
![Screen Shot 2022-03-29 at 8 58 40 AM](https://user-images.githubusercontent.com/86437155/160654550-edd1bc03-f3c5-4887-99f1-61f059fba70d.png)

**Closed by osuleymanova** 2022-03-29 15:58 UTC
