### ISSUE TITLE
Android Basics: tip-calculator

### ISSUE THREAD

**Issue by SaiKummar** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#126] opened 2021-04-27 13:43 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**In which task and step of the codelab can this issue be found?**
In view binding, the final note.

**Describe the problem**
In the final note, it says "The name of the binding class is generated by converting the name of the XML file to **camel case**",
but it should be converted to Pascal case.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
_API version of the emulator:_ 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2021-08-23 22:15
Duplicate of #102

**Comment by osuleymanova** [comment] 2021-08-30 22:08
@SaiKummar 
Thank you for reaching out to us. The issue is fixed and published:

https://developer.android.com/codelabs/basic-android-kotlin-training-tip-calculator?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-tip-calculator#2

**Closed by osuleymanova** 2021-08-30 22:08 UTC
