### ISSUE TITLE
Android Basics: classes-and-inheritance

### ISSUE THREAD

**Issue by yakir4123** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#4] opened 2020-09-24 04:57 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-classes-and-inheritance?return=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-1%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-classes-and-inheritance#4

**In which task and step of the codelab can this issue be found?**
In task *5 . Modify classes in the hierarchy* and *Implement floorArea() for RoundHut* step

**Describe the problem**
Just a minor "typo"
You write in the 3rd line that the area of a circle is 2*PI*R, while its PI * R ^2.

In the code you use you the correct formula, but not when you explain what to do

**Comment by GeneAndGoogle** [comment] 2020-09-28 20:05
Duplicate of #3

**Closed by GeneAndGoogle** 2020-09-28 20:05 UTC
