### ISSUE TITLE
Android Basics: change-app-theme

### ISSUE THREAD

**Issue by amberream** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#133] opened 2021-05-02 22:17 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-2-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fbasic-android-kotlin-training-change-app-theme#4

**In which task and step of the codelab can this issue be found?**
Step 5

**Describe the problem**
The description says, "For your app, you'll use the light colors as the main colors, and the primary colors as the variants."  But under "Update the dark version of your theme" steps 4 and 5 say to use blue_light for both the colorSecondary and colorSecondaryVariant values.  The xml below these steps also show blue_light getting used twice.

**Additional information**
See screenshot
![bug](https://user-images.githubusercontent.com/1459928/116829624-a8b52f80-ab72-11eb-8d97-72fe62c1fd64.JPG)

**Comment by osuleymanova** [comment] 2023-04-06 23:58
Hello @amberream,

Thank you for reaching out to us and sharing your feedback.  
Please take a look at the screenshot below as a proof that the instruction in the codelab corresponds to the code provided in the code snippet:

![Screenshot 2023-04-06 at 4 54 02 PM](https://user-images.githubusercontent.com/86437155/230514338-3162d80e-f5a5-4431-b9c7-1e5b1d4fb48f.png)

The issue is closed as resolved.

**Closed by osuleymanova** 2023-04-06 23:58 UTC
