### ISSUE TITLE
Android Basics: change-app-icon

### ISSUE THREAD

**Issue by KingFuGitHub** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#165] opened 2021-06-24 09:27 UTC
**URL of codelab**

**In which task and step of the codelab can this issue be found?**
in the change the app icon in Unit 2.

**Describe the problem**
There seem to be a mixed up between the foreground and background asset location. The foreground asset should be located in the drawable folder, and the background asset should be stored in the drawable-v24 folder.

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 4.2.1
_API version of the emulator:_ 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by osuleymanova** [comment] 2022-03-28 20:15
Duplicate of #161

**Closed by osuleymanova** 2022-03-28 20:15 UTC
