### ISSUE TITLE
Android Basics: xml-layouts

### ISSUE THREAD

**Issue by jayisreallycool** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#116] opened 2021-04-14 00:00 UTC
**URL of codelab**![image](https://user-images.githubusercontent.com/81924565/114635499-b6fde300-9c79-11eb-8dc8-e38d5eb7f734.png)

**SOLUTIONS**

**replace usage of switch widget**

**Steps to reproduce?**
1. ![image](https://user-images.githubusercontent.com/81924565/114635447-99c91480-9c79-11eb-848d-604b1dfc44ad.png).
2. Click on...
3. See error...
![image](https://user-images.githubusercontent.com/81924565/114635499-b6fde300-9c79-11eb-8dc8-e38d5eb7f734.png)**Versions**
_Android Studio version:_ 4.1.3
_API version of the emulator:_ 19 kit kat 

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by jtavva** [comment] 2021-04-20 20:23
@jayisreallycool 
Thank you for reaching out to us.
Could you please check the suggested solution for #118 and update us if it solved your problem.

**Comment by osuleymanova** [comment] 2021-11-24 20:22
The issue is closed as no further update was provided.

**Closed by osuleymanova** 2021-11-24 20:22 UTC
Labels: question
