### ISSUE TITLE
Android Basics: Done button missing -- change-app-theme

### ISSUE THREAD

**Issue by ghost** [google-developer-training/android-basics-kotlin-tip-calculator-app-solution#75] opened 2021-02-17 08:35 UTC
**URL of codelab**
https://developer.android.com/codelabs/basic-android-kotlin-training-change-app-theme?hl=ko#8

**In which task and step of the codelab can this issue be found?**
last step

**Describe the problem**
there is no escape btn
 ![제목 없음](https://user-images.githubusercontent.com/76655411/108177340-73d63680-7146-11eb-852d-a9aa23782339.png)

Thanks for your very useful lecture

**Comment by osuleymanova** [comment] 2021-11-24 23:55
@ghost
The issue that you presented to us is important, and I thank you for bringing it to our attention. Could you please let us know on what OS and browser it happened?

**Comment by osuleymanova** [comment] 2022-03-25 22:48
@ghost
The issue is closed as no further clarification of it was provided.

**Closed by osuleymanova** 2022-03-25 22:48 UTC
Labels: DAC renderring
